name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        operating-system: [windows-latest, ubuntu-latest, macos-latest]
        lazarus-versions: [stable, 2.0.10, 2.0.8, 1.8.4]
    
    runs-on: ${{ matrix.operating-system }}

    steps:
      - uses: actions/checkout@v2

      - name: Install Lazarus
        uses: gcarreno/setup-lazarus@v3.0.2
        with:
          lazarus-version: ${{ matrix.lazarus-versions }}

      - name: Build Battlefield
        working-directory: battlefield
        run: lazbuild -B Battlefield.lpi

      - name: Build SelftestDataCreate
        working-directory: selftest_data_create
        run: lazbuild -B SelftestDataCreate.lpi
