name: build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        lazarus: [stable, 2.0.12, 2.0.10, 2.0.8, 1.8.4]
        exclude:
          # They say that Lazarus < 2.0.8 is not supported in setup-lazarus action for macOS
          - os: macos-latest
            lazarus: 1.8.4
          # For Windows, FPC 3.2.0 is minimum supported version because of the following bugs
          # with wrong type declarations in MMSystem unit:
          # - https://bugs.freepascal.org/view.php?id=33823
          # - https://bugs.freepascal.org/view.php?id=35469
          - os: windows-latest
            lazarus: 1.8.4
          - os: windows-latest
            lazarus: 2.0.8

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Install Lazarus
        uses: gcarreno/setup-lazarus@v3.0.2
        with:
          lazarus-version: ${{ matrix.lazarus }}

      - name: Build Battlefield
        working-directory: battlefield
        run: lazbuild -B Battlefield.lpi

      - name: Build SelftestDataCreate
        working-directory: selftest_data_create
        run: lazbuild -B SelftestDataCreate.lpi
